### ISSUE TITLE
getState() is undefined

### ISSUE THREAD

**Issue by lamogura** [leoasis/redux-immutable-state-invariant#27]
Got this error when adding this to my dev middleware. 

```
const middleware = [
  require('redux-immutable-state-invariant').default,
  thunk,
  promise,
]
const store = createStore(
  rootReducer,
  initialState,
  compose(
    applyMiddleware(...middleware),
    DevTools.instrument() // Enable Redux DevTools
  )
)
```

"redux":   "version": "3.6.0"

![screen shot 2017-05-12 at 09 27 32](https://cloud.githubusercontent.com/assets/1475223/25977254/532646e4-36f5-11e7-931c-277f623e6737.png)

**Comment by leoasis** [comment]
Remember that what you import from this library is a "middleware factory", which means it's a function you have to call _to get the middleware to inject in Redux_. So your example should be changed to be like this:

```js
const middleware = [
  require('redux-immutable-state-invariant').default(), // <-- Notice the parens here
  thunk,
  promise,
]
const store = createStore(
  rootReducer,
  initialState,
  compose(
    applyMiddleware(...middleware),
    DevTools.instrument() // Enable Redux DevTools
  )
)
```

**Comment by leoasis** [comment]
Closing since it's been a while this has been open without answer. Feel free to reopen if you still have issues!
