### ISSUE TITLE
Does not seem to detect direct manipulation of a value

### ISSUE THREAD

**Issue by omnidan** [leoasis/redux-immutable-state-invariant#4]
I tried adding your library to my `redux-undo-boilerplate` and was testing it out by [adding `state++` in my `counter` reducer](https://github.com/omnidan/redux-undo-boilerplate/blob/enforce-immutable/src/reducers/counter.js#L7). Unfortunately, this library does not seem to detect this state manipulation.

You can test it out by cloning the `enforce-immutable` branch and running it with `npm run dev`: https://github.com/omnidan/redux-undo-boilerplate/tree/enforce-immutable

**Comment by leoasis** [comment]
You're not mutating the state there, since a number is immutable in Javascript natively. What you are mutating there is the local variable reference `state` that _holds_ the state.

That is perfectly valid stuff to do inside a reducer, and it won't cause any problems with redux at all.

**Comment by omnidan** [comment]
@leoasis interesting. I did not know that. Well that explains it then, so I'll close it :grin:

**Comment by omnidan** [comment]
@leoasis okay, I must be doing something really wrong. I tried what you told me to do, but it doesn't seem to detect that either: https://github.com/omnidan/redux-undo-boilerplate/commit/4203de947ae792657fcf3e48d6c73898b4e7a300

**Comment by leoasis** [comment]
Well, that seems to actually _be_ a bug here. I'm taking a look and will push a fix. Thanks for reporting!

**Comment by omnidan** [comment]
@leoasis no problem :grin: let me know when it's fixed and I'll test it for you (or you can just use https://github.com/omnidan/redux-undo-boilerplate/commit/4203de947ae792657fcf3e48d6c73898b4e7a300)

**Comment by leoasis** [comment]
@omnidan Alright, pushed some changes to master, would you mind checking if that now works for you? I realized that I was checking the mutations taking into account the returning state as well as the previous, but it turns out that I only needed to check the reference and the snapshot of the previous state to see if they are different.

Anyway, it should be working, added some new tests and they all pass, but if it doesn't (or it breaks with something else) let me know!

**Comment by omnidan** [comment]
@leoasis huh, I can't seem to be able to install the `master` branch with npm - I tried:

```sh
npm install leoasis/redux-immutable-state-invariant
npm install leoasis/redux-immutable-state-invariant#master
npm install git://github.com/leoasis/redux-immutable-state-invariant
npm install git://github.com/leoasis/redux-immutable-state-invariant#master
```

None of these seem to work, they all say `redux-immutable-state-invariant@1.1.0 node_modules/redux-immutable-state-invariant` but then don't install it at all. Would you mind testing it with my boilerplate and releasing a new version? :grin:

**Comment by omnidan** [comment]
Actually they do install something, but it doesn't seem to have any source code, just an `example` folder, `README.md`, `LICENSE.md` and `package.json` :scream:

**Comment by leoasis** [comment]
Ah yes, you're right, since it gets it from the repo but it doesn't have the compiled files. Will test your repo locally and publish a release

**Comment by omnidan** [comment]
Ahh that makes sense. I was getting kinda confused about this :stuck_out_tongue: Thanks a lot!

**Comment by leoasis** [comment]
Tried it on your repo and seems to work now, released! https://github.com/leoasis/redux-immutable-state-invariant/releases. Let me know if you find something else!

Thanks again for filing the issue!

**Comment by omnidan** [comment]
@leoasis hm... I just installed `1.1.1` but it still does not seem to detect the mutation for me. Anything you changed in my code to make it work?

**Comment by leoasis** [comment]
Yes, it is working for me. Cloned your repo, went to the `enforce-immutable` branch, then did: `npm install` and `npm run dev`. Then I click the + button in the site and I see the mutation error.

**Comment by omnidan** [comment]
@leoasis Sorry - it was a stupid mistake on my side. I started it in production mode, it works fine in dev mode :stuck_out_tongue: This can be closed then!

*Time to get some :coffee:*

**Comment by leoasis** [comment]
Glad it worked, and thanks again for finding (and filing) this bug :D

**Comment by omnidan** [comment]
You're welcome :grin: Thanks for fixing it, I'll add your project to my boilerplate now.

**Comment by leoasis** [comment]
Thanks for using it/mentioning :D
