### ISSUE TITLE
Doesn't seem to detect reference updates (equal, but not identical)

### ISSUE THREAD

**Issue by nevir** [leoasis/redux-immutable-state-invariant#5]
```js
reducer(state = {}, action) {
  // I would expect this to trigger an error, but it doesn't
  state.foo = {};
  return state;
}
```

One I give it differing values, it does:

```js
let count = 0;
reducer(state = {}, action) {
  // boom
  state.foo = {count: count++};
  return state;
}
```

**Comment by leoasis** [comment]
Nice catch, will try to fix it soon

**Comment by nevir** [comment]
Awesome :)

**Comment by leoasis** [comment]
@nevir I've pushed some changes to the logic to detect mutations, and this should be fixed. I'll release a new version soon but if you want/need this now you can test with current master. Feel free to reopen if this is still not working!
